#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["API.Gateway/API.Gateway.csproj", "API.Gateway/"]
COPY ["CommonLib.Configurations/CommonLib.Configurations.csproj", "CommonLib.Configurations/"]
COPY ["CommonLib.Constants/CommonLib.Constants.csproj", "CommonLib.Constants/"]
COPY ["CommonLib.Enum/CommonLib.Enums.csproj", "CommonLib.Enum/"]
RUN dotnet restore "./API.Gateway/API.Gateway.csproj"
COPY . .
WORKDIR "/src/API.Gateway"
RUN dotnet build "./API.Gateway.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./API.Gateway.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "API.Gateway.dll"]